name: Run Trading Bot

on:
  schedule:
    - cron: '0 */4 * * *'  # Run every 4 hours
  workflow_dispatch:  # Allow manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Add custom User-Agent headers for Binance API
        run: |
          echo 'import os
          import requests
          
          # Monkey patch requests to add User-Agent header
          original_get = requests.get
          
          def get_with_headers(*args, **kwargs):
              if "headers" not in kwargs:
                  kwargs["headers"] = {}
              
              kwargs["headers"]["User-Agent"] = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
              return original_get(*args, **kwargs)
          
          requests.get = get_with_headers' > patch_requests.py
      
      - name: Run trading bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python -c "import patch_requests"
          python app.py